# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x08keyvalue\"?\n\rPutKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x12\n\nis_replica\x18\x03 \x01(\x08\"-\n\x0cPutKeyReturn\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0fTinhTongRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\x12\t\n\x01\x63\x18\x03 \x01(\t\" \n\x0eKetQuaTinhTong\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\x05\"\x16\n\x07Message\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"3\n\x10\x44\x65leteKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\nis_replica\x18\x02 \x01(\x08\"\x16\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\t\"\x14\n\x12HealthCheckRequest\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x0e\n\x0c\x45mptyRequest\")\n\x14\x46ullSnapshotResponse\x12\x11\n\tdata_json\x18\x01 \x01(\t2\x93\x03\n\x08KeyValue\x12\x41\n\x08TinhTong\x12\x19.keyvalue.TinhTongRequest\x1a\x18.keyvalue.KetQuaTinhTong\"\x00\x12;\n\x06PutKey\x12\x17.keyvalue.PutKeyRequest\x1a\x16.keyvalue.PutKeyReturn\"\x00\x12*\n\x06GetKey\x12\r.keyvalue.Key\x1a\x0f.keyvalue.Value\"\x00\x12<\n\tDeleteKey\x12\x1a.keyvalue.DeleteKeyRequest\x1a\x11.keyvalue.Message\"\x00\x12L\n\x0b\x43heckHealth\x12\x1c.keyvalue.HealthCheckRequest\x1a\x1d.keyvalue.HealthCheckResponse\"\x00\x12O\n\x13RequestFullSnapshot\x12\x16.keyvalue.EmptyRequest\x1a\x1e.keyvalue.FullSnapshotResponse\"\x00\x42\x32\n\x19io.grpc.examples.keyvalueB\rkeyvalueProtoP\x01\xa2\x02\x03RTGb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031io.grpc.examples.keyvalueB\rkeyvalueProtoP\001\242\002\003RTG'
  _globals['_PUTKEYREQUEST']._serialized_start=24
  _globals['_PUTKEYREQUEST']._serialized_end=87
  _globals['_PUTKEYRETURN']._serialized_start=89
  _globals['_PUTKEYRETURN']._serialized_end=134
  _globals['_TINHTONGREQUEST']._serialized_start=136
  _globals['_TINHTONGREQUEST']._serialized_end=186
  _globals['_KETQUATINHTONG']._serialized_start=188
  _globals['_KETQUATINHTONG']._serialized_end=220
  _globals['_MESSAGE']._serialized_start=222
  _globals['_MESSAGE']._serialized_end=244
  _globals['_KEY']._serialized_start=246
  _globals['_KEY']._serialized_end=264
  _globals['_DELETEKEYREQUEST']._serialized_start=266
  _globals['_DELETEKEYREQUEST']._serialized_end=317
  _globals['_VALUE']._serialized_start=319
  _globals['_VALUE']._serialized_end=341
  _globals['_HEALTHCHECKREQUEST']._serialized_start=343
  _globals['_HEALTHCHECKREQUEST']._serialized_end=363
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=365
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=402
  _globals['_EMPTYREQUEST']._serialized_start=404
  _globals['_EMPTYREQUEST']._serialized_end=418
  _globals['_FULLSNAPSHOTRESPONSE']._serialized_start=420
  _globals['_FULLSNAPSHOTRESPONSE']._serialized_end=461
  _globals['_KEYVALUE']._serialized_start=464
  _globals['_KEYVALUE']._serialized_end=867
# @@protoc_insertion_point(module_scope)
