# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import demo_pb2 as demo__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in demo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KeyValueStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TinhTong = channel.unary_unary(
                '/keyvalue.KeyValue/TinhTong',
                request_serializer=demo__pb2.TinhTongRequest.SerializeToString,
                response_deserializer=demo__pb2.KetQuaTinhTong.FromString,
                _registered_method=True)
        self.PutKey = channel.unary_unary(
                '/keyvalue.KeyValue/PutKey',
                request_serializer=demo__pb2.PutKeyRequest.SerializeToString,
                response_deserializer=demo__pb2.PutKeyReturn.FromString,
                _registered_method=True)
        self.GetKey = channel.unary_unary(
                '/keyvalue.KeyValue/GetKey',
                request_serializer=demo__pb2.Key.SerializeToString,
                response_deserializer=demo__pb2.Value.FromString,
                _registered_method=True)
        self.DeleteKey = channel.unary_unary(
                '/keyvalue.KeyValue/DeleteKey',
                request_serializer=demo__pb2.DeleteKeyRequest.SerializeToString,
                response_deserializer=demo__pb2.Message.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/keyvalue.KeyValue/CheckHealth',
                request_serializer=demo__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=demo__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.RequestFullSnapshot = channel.unary_unary(
                '/keyvalue.KeyValue/RequestFullSnapshot',
                request_serializer=demo__pb2.EmptyRequest.SerializeToString,
                response_deserializer=demo__pb2.FullSnapshotResponse.FromString,
                _registered_method=True)


class KeyValueServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TinhTong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestFullSnapshot(self, request, context):
        """RPC mới cho việc yêu cầu snapshot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TinhTong': grpc.unary_unary_rpc_method_handler(
                    servicer.TinhTong,
                    request_deserializer=demo__pb2.TinhTongRequest.FromString,
                    response_serializer=demo__pb2.KetQuaTinhTong.SerializeToString,
            ),
            'PutKey': grpc.unary_unary_rpc_method_handler(
                    servicer.PutKey,
                    request_deserializer=demo__pb2.PutKeyRequest.FromString,
                    response_serializer=demo__pb2.PutKeyReturn.SerializeToString,
            ),
            'GetKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKey,
                    request_deserializer=demo__pb2.Key.FromString,
                    response_serializer=demo__pb2.Value.SerializeToString,
            ),
            'DeleteKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKey,
                    request_deserializer=demo__pb2.DeleteKeyRequest.FromString,
                    response_serializer=demo__pb2.Message.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=demo__pb2.HealthCheckRequest.FromString,
                    response_serializer=demo__pb2.HealthCheckResponse.SerializeToString,
            ),
            'RequestFullSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestFullSnapshot,
                    request_deserializer=demo__pb2.EmptyRequest.FromString,
                    response_serializer=demo__pb2.FullSnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'keyvalue.KeyValue', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('keyvalue.KeyValue', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KeyValue(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TinhTong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyvalue.KeyValue/TinhTong',
            demo__pb2.TinhTongRequest.SerializeToString,
            demo__pb2.KetQuaTinhTong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PutKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyvalue.KeyValue/PutKey',
            demo__pb2.PutKeyRequest.SerializeToString,
            demo__pb2.PutKeyReturn.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyvalue.KeyValue/GetKey',
            demo__pb2.Key.SerializeToString,
            demo__pb2.Value.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyvalue.KeyValue/DeleteKey',
            demo__pb2.DeleteKeyRequest.SerializeToString,
            demo__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyvalue.KeyValue/CheckHealth',
            demo__pb2.HealthCheckRequest.SerializeToString,
            demo__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestFullSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/keyvalue.KeyValue/RequestFullSnapshot',
            demo__pb2.EmptyRequest.SerializeToString,
            demo__pb2.FullSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
